Repository lab-antwerp-1/pc-group2, pull requests merged in 2021-10, with the labels that each got.

#1 created backlog.md design.md development-startagy.md and issues.md in planning/
  .cspell.json
  .github/workflows/lint-and-validate.yml
  .markdownlint.jsonc
  package-lock.json
  pages/about.html
  planning/backlog.md
  planning/design.md
  planning/developement-strategy.md
  planning/issues.md
  styles/index.css
Labels: group

#10 modified development startagy.md
  .cspell.json
  planning/backlog.md
  planning/developement-strategy.md
Labels: group

#15 add logo.png and student.jpg to .assets/ added markers to index.html created style.css
  assets/Logo.png
  assets/student.jpg
  index.html
  styles/style.css
Labels: group

#18 Aviv logo image
  .cspell.json
  .vscode/settings.json
  index.html
  styles/style.css
Labels: group, css

#19 Mervatnew update adding description part
  index.html
Labels: group

#22 updates
  index.html
  styles/style.css
Labels: group, css, html
